async_checkpointing: true
checkpoint_every_steps: 10000
coeffs_fn_dim: 2
collocation_size: 128
data_dir: /workspaces/deeprte/data/tfds
data_sharding: !!python/tuple
- !!python/tuple
  - data
  - fsdp
  - tensor
data_shuffle_seed: 42
dataset_name: rte/g0.8-sigma_a3-sigma_t6
dataset_type: tfds
dcn_data_parallelism: -1
dcn_fsdp_parallelism: 1
dcn_tensor_parallelism: 1
decay_steps: 500001
enable_checkpoint_standard_logger: true
enable_data_shuffling: true
enable_emergency_checkpoint: false
enable_single_replica_ckpt_restoring: false
eval_batch_size: 4
eval_every_steps: 50000
eval_split: train[80%:]
global_batch_size: 8
grain_worker_buffer_size: 1
grain_worker_count: 4
ici_data_parallelism: 1
ici_fsdp_parallelism: -1
ici_tensor_parallelism: 1
learning_rate: 0.001
load_full_state_path: ''
load_parameters_path: ''
local_checkpoint_dir: ''
local_checkpoint_every_steps: 10000
log_every_steps: 1000
mesh_axes: !!python/tuple
- data
- fsdp
- tensor
micro_steps: 2
mlp_dim: 128
normalization: 0.81073660406395
num_heads: 2
num_mlp_layers: 4
num_scattering_layers: 2
num_train_steps: 500001
optical_depth_dim: 2
optimizer: adam
per_device_batch_size: 1
position_coords_dim: 2
qkv_dim: 64
repeat_batch: 1
save_checkpoints: true
scattering_dim: 16
schedule: cosine_decay
seed: 42
subcollocation_size: 128
train_split: train[:80%]
velocity_coords_dim: 2
