services:
  deeprte:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/deeprte:cached
      - rte_data:/deeprte/data
      - venv:/deeprte/.venv
      - uv-cache:/home/deeprte/.cache/uv
    command: "sleep infinity"
    shm_size: 1gb
    gpus: all

volumes:
  venv:
  rte_data:
    external: true
  uv-cache:
    external: true
